lang_name: "Deutsch"
title: "Solidarity will win!"
subtitle: "Zusammen gegen die Angriffe auf Geflüchtete!"
event: "08. Februar 2025, 13:00 Uhr, am Steindamm 45"
direction: ltr
date_format: "%e. %b %Y"